g gitoversight-state -
g gitoversight-authority -
g gitoversight-notifications -
g gitoversight-api -
g gitoversight-worker -
g gitoversight-checkpoint -
g gitoversight-notify -
u gitoversight-api - "Git Oversight API" /var/lib/gitoversight-api /usr/sbin/nologin
u gitoversight-worker - "Git Oversight Worker" /var/lib/gitoversight-worker /usr/sbin/nologin
u gitoversight-checkpoint - "Git Oversight Checkpoint" /var/lib/gitoversight-checkpoint /usr/sbin/nologin
u gitoversight-notify - "Git Oversight Notifications" /var/lib/gitoversight-notify /usr/sbin/nologin
m gitoversight-api gitoversight-state
m gitoversight-api gitoversight-worker
m gitoversight-api gitoversight-checkpoint
m gitoversight-api gitoversight-authority
m gitoversight-worker gitoversight-authority
m gitoversight-api gitoversight-notifications
m gitoversight-notify gitoversight-notifications
